
GET http://localhost:3000/users

### Get Contact by ID

GET http://localhost:3000/users/696c10c74b2f8cb58fcf9437

### Create Contacts

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Tycoon",
    "lastName": "Paully",
    "email": "lawanipaul88@gmail.com",
    "favoriteColor" : "Yellow",
    "birthday": "03-06-1990"
}

### Put Contacts

PUT http://localhost:3000/users/696c0e0e4b2f8cb58fcf9436 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Tycoon",
    "lastName": "Paully",
    "email": "lawanipaul88@gmail.com"

}

### Delete Contacts

DELETE http://localhost:3000/users/696c12640de6c9d28af2ec2d